---
- name: Install Uptick Instance
  hosts: all

  tasks:

  - name: Install required packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - npm
      - nodejs
      - nodejs-mysql

  - name: be sure firewalld is disabled
    systemd: name=firewalld enabled=no

  - name: be sure firewalld is stopped
    systemd: name=firewalld state=stopped
    ignore_errors: yes
    
  - selinux:
      state: disabled

  - name: Create directory for code
    command: mkdir -p /var/www/projects

  - git:
    repo: https://github.com/mjastad/uptick.git
    dest: /var/www/projects
    
  - name: Change directory permissions
    command: chmod -R 755 /var/www/projects/uptick
    
  - name: Change nodejs configs
    command: sed -i -e 's/DB_SERVER_IPADDRESS/10.21.12.242/g' /var/www/projetcs/config/mysqlConfig.js
    
  - name: Change nodejs configs
    command: sed -i -e 's/DB_USER/root/g' /var/www/projetcs/config/mysqlConfig.js
    
  - name: Change nodejs configs
    command: sed -i -e 's/DB_PASSWORD/nutanix\/4u/g' /var/www/projetcs/config/mysqlConfig.js
    
  - name: Change nodejs configs
    command: sed -i -e 's/DB_NAME/Uptick/g' /var/www/projetcs/config/mysqlConfig.js

  - name: Build nodejs app
    command: npm build /var/www/projects/uptick

  - name: Install forever npm
    command: npm install -g forever
    
  - name: Run nodejs server
    command: forever start /var/www/projects/uptick/server.js

  - git:
    repo: https://github.com/mjastad/uptick.git
    dest: /usr/share/nginx/html/

  - name: Move cloned repo
    command: mv /usr/share/nginx/html/uptick/* /usr/share/nginx/html/
    
  - name: Change directory permissions
    command: chmod -R 755 /usr/share/nginx/html/
    
  - name: Change nodejs configs
    command: sed -i -e 's/NODE_SERVER_IP_ADDRESS/localhost/g' /usr/share/nginx/html/js/data.js

  - name: Start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes
