---
- hosts: digitalocean
  vars:
    do_token: "{{ lookup('env','DO_API_KEY') }}"
    droplets:
      - swarm-manager-1
      - swarm-manager-2
      - swarm-worker-1
      - swarm-worker-2
      - swarm-worker-3

  tasks:

  - name: Ensure key exists at digitalocean
    digital_ocean:
      state: present
      command: ssh
      name: ansible
      ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      api_token: "{{ do_token }}"
    register: ansible

  - name: Destroy docker nodes
    digital_ocean:
      state: absent
      command: droplet
      name: "{{ item }}"
      unique_name: yes
      size_id: 512mb
      region_id: sfo2
      image_id: centos-7-2-x64
      ssh_key_ids: "{{ ansible.ssh_key.id }}"
      api_token: "{{ do_token }}"
    with_items: "{{ droplets }}"
