---
- name: Install Docker
  hosts: all

  tasks:

  - name: Update packages on host(s)
    yum:
      name: '*'
      state: latest

  - name: Add docker upstream repo
    yum_repository:
      name: docker-ce-stable
      description: Docker Repository
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: 1
      gpgcheck: 1
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install docker engine on docker hosts
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-python
      - iscsi-initiator-utils

  - name: Start iscsi initator service
    service:
      name: iscsid
      state: started
      enabled: yes

  - name: Start and enable docker engine
    service:
      name: docker
      state: started
      enabled: yes

  - name: Create systemd tmpfs files
    command: systemd-tmpfiles --create

  - name: Enable Nutanix volume plugin for containers
    command: docker plugin install --grant-all-permissions ntnx/nutanix_volume_plugin:latest PRISM_IP="192.168.0.5" DATASERVICES_IP="192.168.0.6" PRISM_USERNAME="docker" PRISM_PASSWORD='C0nt@1n!' DEFAULT_CONTAINER="Containers" --alias nutanix
    args:
      creates: /tmp/.docker_nutanix_plugin_enabled
