---
- name: Install Docker
  hosts: all

  tasks:

  - name: Update packages on host(s)
    yum:
      name: '*'
      state: latest

  - name: Add docker upstream repo
    yum_repository:
      name: docker-ce-stable
      description: Docker Repository
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: 1
      gpgcheck: 1
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install docker engine on docker hosts
    yum:
      name: docker-ce
      state: present

  - name: Start and enable docker engine
    service:
      name: docker
      state: started
      enabled: yes
